name: Docker Login Counter App
on: 
  push:
    branches:
      - main

env: 
    REPO_OWNER: 'paritosh-pranjal'    

jobs:
    frontend:
        name: frontend
        defaults:
          run:
            working-directory: frontend
        strategy:
            matrix:
                nodejs_version: [18]
                operating_system: [ubuntu-latest]
        runs-on: ${{ matrix.operating_system }}
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Setup NodeJS Version - ${{ matrix.nodejs_version }}
          uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.nodejs_version }}
        
        - name: Cache NPM dependecies
          uses: actions/cache@v3
          with:
            path: frontend/node_modules
            key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}

        - name: Install Dependencies
          run: npm install

    code-coverage:
      defaults:
        run:
          working-directory: frontend
      strategy:
            matrix:
                nodejs_version: [18]
                operating_system: [ubuntu-latest]
      runs-on: ${{ matrix.operating_system }}
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Setup NodeJS Version - 18
          uses: actions/setup-node@v3
          with:
            node-version: 18
        
        - name: Cache NPM dependecies
          uses: actions/cache@v3
          with:
            path: node_modules
            key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}   

        - name: Install Dependencies
          run : npm install  

        - name: Check Code Coverage
          run: npm run test

        - name: Archive Test Result
          uses: actions/upload-artifact@v3
          with:
            name: Code-Coverage-Result
            path: coverage
            retention-days: 5

    docker:
      name: Build the Docker image
      needs: [frontend,code-coverage]
      defaults:
        run:
          working-directory: frontend
      runs-on: ubuntu-latest
      permissions: 
          packages: write
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
    
        - name: Dockerhub Login
          uses: docker/login-action@v3
          with:
            username: ${{ vars.ASSIGNMENT_USERNAME }}
            password: ${{ secrets.ASSIGNMENT_PASSWORD }}

        - name: Dockerhub Build for Testing
          uses: docker/build-push-action@v4
          with:
            context: ./frontend
            push: false
            tags: ${{ vars.ASSIGNMENT_USERNAME}}/counter-app:${{ github.sha }}
      
        - name: Docker Image testing
          run: |
            docker images
            docker run --name counter-app-assignment -d  \
                ${{ vars.ASSIGNMENT_USERNAME}}/counter-app:${{ github.sha }}
            docker container ps 
            docker container ps -a
      
        - name: GHCR Login
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GITHUB_TOKEN }}
            
        - name: Push the docker image to dockerhub and ghcr
          uses: docker/build-push-action@v4
          with:
            context: ./frontend
            push: true
            tags: |
                ${{ vars.ASSIGNMENT_USERNAME}}/counter-app:${{ github.sha }}
                ghcr.io/${{env.REPO_OWNER}}/counter-app:${{ github.sha }}